# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a7f3f2f42f6bdcc713db0c135e97fbdc73243e908b3f8a303d385e7bb4716d0c9d7b4c896d9e38f7b2004688cdb83155398401a07f18cf6545fbea77d91bb2e2

test:
  secret_key_base: acd5175077011f4cd48569f36200873c48f792b501d9978c6288ee40d742f233a89f3fafd4ed361fb0305180b0c01bb331a3fdfbf9172a243bf6ae819a839da0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
